In [1]:
import numpy as np

In [2]:
b = np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [3]:
b[3]

4

In [4]:
type(np.array([1,2,3,4,5]))

# In numpy array is called called ndarray as n-dimentional array

numpy.ndarray

The above array is by default 0 or 1 dimensional as 0 or 1 dimensional array are one & the same.
- Accessing the elements from 1 dimensional array is easy as they have only x axis.
- Hence if we would want to access 4, 4 is present at x = 3 i.e. b[3]

In [5]:
a = np.array([[1,2,3, 4], [3,4,6, 9]])
a

array([[1, 2, 3, 4],
       [3, 4, 6, 9]])

2-D array can be represented visually as:

x-axis 0 1 2 3
\
y-axis
\
0
\
1

- The co-ordinates of 1 would be x=0, y=0.
- The co-ordinates of 9 would be x=1, y=3

In [6]:
# How to extract 1 from the above array

a[0][0]

1

In [7]:
a[1][3]

9

In [8]:
c = np.array([1,2,3,4,5], ndmin=5)
c

array([[[[[1, 2, 3, 4, 5]]]]])

- Here we have specified dimension value along with the array.
- Hence it has considered the array as 5 dimensional.

In [9]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr.ndim

2

The above array is of 2 dimensions, as we can say that there are 3 rows & 3 columns so the dimension is 3, but it's not.
- To identify the dimensions of the array we can simply look at the opening & closing [].
- If there are 2 [[ ]] then it is of 2 dimensions.
- If there are 3 [[[ ]]] then it's a 3 dimension array.

In [11]:
## Generate the random integers data between the given range of a given size

np.random.randint(low=1, high=20, size=(4,4))

array([[ 8, 15,  5, 19],
       [ 1,  8, 19,  4],
       [11,  8, 12, 10],
       [18, 12,  8,  1]])

In [12]:
np.random.randint(low=1, high=20, size=(4,4,2))

array([[[ 1, 17],
        [19, 13],
        [ 4,  7],
        [14,  7]],

       [[ 1, 19],
        [ 6,  6],
        [ 7, 13],
        [ 4,  3]],

       [[17,  5],
        [16, 13],
        [15, 19],
        [13,  2]],

       [[15, 11],
        [ 3,  2],
        [17, 10],
        [13,  2]]])

- Now here the above array is of 3 dimensions as there are 3 [[[ ]]] at the begining & end of array.
- Now to visualize the above array in axis forms we can consider it from right to left i.e. (4,4,2) --> (z, y, x)
- last element will give x-axis item count means on x-axis 2 elements are there.
- middle element will give y-axis count means on y-axis 4 elements are there.
- The first element will give z-axis count means how many [ ] of x-y axis should be there i.e. 4

- Hence it can be interpreted as there should be 4 array of 4*2 dimensions.

In [13]:
l = [1,2,3,4,"Abc", "FSDS", 2023-24, 19.8]
a = np.array(l)
a

array(['1', '2', '3', '4', 'Abc', 'FSDS', '1999', '19.8'], dtype='<U32')

We can convert any list into an array but the only catch here is that it will consider all the elements as a string. It will not keep its original datatype in array

In [14]:
a[0] +a[1]

'12'

In [15]:
np.random.rand(3,2)

array([[0.61401454, 0.57043891],
       [0.56582766, 0.75433573],
       [0.59832452, 0.72817919]])

- random.rand() will give the random numbers
- random.randn() will give the numbers whose distribution is normal

In [16]:
a = np.random.randn(4,4)
a

array([[-0.44837709, -0.75648131, -0.07175639,  2.05508909],
       [ 0.23639443,  0.84874587,  1.75324715, -1.0565744 ],
       [ 1.13056654,  0.72726321,  0.8146195 , -0.05239287],
       [-1.69701045,  0.14644561, -0.66143636,  0.69101622]])

Reshape() will only change the columns or rows size, but not the data points size.
- The above matrix contains 4*4 = 16 elements.
- So we can reshape the above array from 4*4 to 8*2 or 2*8 but not in 3*4 or 5*4 as this will change the data elements size.

In [17]:
a.reshape(8,3)

ValueError: cannot reshape array of size 16 into shape (8,3)

In [18]:
a.reshape(2,2,4)

array([[[-0.44837709, -0.75648131, -0.07175639,  2.05508909],
        [ 0.23639443,  0.84874587,  1.75324715, -1.0565744 ]],

       [[ 1.13056654,  0.72726321,  0.8146195 , -0.05239287],
        [-1.69701045,  0.14644561, -0.66143636,  0.69101622]]])

Numpy will detect automatic factor with first element if we give any -ve number as second parameter in reshape()

In [19]:
a.reshape(2,-1)

array([[-0.44837709, -0.75648131, -0.07175639,  2.05508909,  0.23639443,
         0.84874587,  1.75324715, -1.0565744 ],
       [ 1.13056654,  0.72726321,  0.8146195 , -0.05239287, -1.69701045,
         0.14644561, -0.66143636,  0.69101622]])

In [20]:
a

array([[-0.44837709, -0.75648131, -0.07175639,  2.05508909],
       [ 0.23639443,  0.84874587,  1.75324715, -1.0565744 ],
       [ 1.13056654,  0.72726321,  0.8146195 , -0.05239287],
       [-1.69701045,  0.14644561, -0.66143636,  0.69101622]])

In [21]:
a[3:6]

array([[-1.69701045,  0.14644561, -0.66143636,  0.69101622]])

**Reversing of an array same as list reversing**

In [22]:
a[::-1]

array([[-1.69701045,  0.14644561, -0.66143636,  0.69101622],
       [ 1.13056654,  0.72726321,  0.8146195 , -0.05239287],
       [ 0.23639443,  0.84874587,  1.75324715, -1.0565744 ],
       [-0.44837709, -0.75648131, -0.07175639,  2.05508909]])

In [23]:
a1 = np.array([[1,2,3], [4,5,6]])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
a1[1,1:]

array([5, 6])

In [25]:
a1[:, 1:]

array([[2, 3],
       [5, 6]])

In [26]:
a2 = np.random.randint(2,90, (6,5))
a2

array([[20, 68, 34, 11, 35],
       [24, 41, 78, 30, 59],
       [73, 27,  9, 36, 49],
       [40, 80, 30, 48, 23],
       [60, 21, 36,  5, 68],
       [83, 32, 41, 40, 47]])

**Conditional slicing**

In [27]:
a2[a2>40]

array([68, 41, 78, 59, 73, 49, 80, 48, 60, 68, 83, 41, 47])

In [28]:
a2[0,1] = 54
a2

array([[20, 54, 34, 11, 35],
       [24, 41, 78, 30, 59],
       [73, 27,  9, 36, 49],
       [40, 80, 30, 48, 23],
       [60, 21, 36,  5, 68],
       [83, 32, 41, 40, 47]])

In [29]:
a3 = np.random.randint(1,10, (3,3))
a4 = np.random.randint(10,30, (3,3))

In [30]:
a3

array([[2, 7, 9],
       [4, 7, 1],
       [8, 5, 8]])

In [31]:
a4

array([[21, 15, 27],
       [20, 19, 28],
       [23, 14, 13]])

In [32]:
a3*a4

array([[ 42, 105, 243],
       [ 80, 133,  28],
       [184,  70, 104]])

a3*a4 will directly multiply each elements of the two matrix.
\
But if we want to do matrix multiplication then we have to use @.

In [33]:
a3@a4

array([[389, 289, 367],
       [247, 207, 317],
       [452, 327, 460]])

In [34]:
a3/0

C:\Users\OWNER\AppData\Local\Temp\ipykernel_10572\2709798280.py:1: RuntimeWarning: divide by zero encountered in divide
  a3/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [35]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
a4 = np.ones((4,3))
a4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**broadcasting operation** it will apply the function row wise to all rows

In [37]:
a4 + np.array([2,3,4])

array([[3., 4., 5.],
       [3., 4., 5.],
       [3., 4., 5.],
       [3., 4., 5.]])

**Broadcasting operation column wise**

In [38]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [39]:
a4 + np.array([[1,2,3,4]]).T

array([[2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.],
       [5., 5., 5.]])

In [40]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

Here in range function we cant use float numbers. But in np we have that facility.

In [41]:
np.arange(1.7,10.7, 2.2)

array([ 1.7,  3.9,  6.1,  8.3, 10.5])

**Linspace will give range of no from a given range**

In [43]:
np.linspace(2,3, num = 50, retstep = True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

**Range of logarithmic numbers of from range, size and base**

In [47]:
np.logspace(2,3,num = 10, base = 10)

array([ 100.        ,  129.1549665 ,  166.81005372,  215.443469  ,
        278.25594022,  359.38136638,  464.15888336,  599.48425032,
        774.26368268, 1000.        ])

**Identity matrix of size 5**

In [48]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])